// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBCuCUWenm0gZptXSbKZcHBycoxnyen0E',
    appId: '1:175735179668:web:8183c8a048d418f6a9e781',
    messagingSenderId: '175735179668',
    projectId: 'pawtrack-59d07',
    authDomain: 'pawtrack-59d07.firebaseapp.com',
    storageBucket: 'pawtrack-59d07.firebasestorage.app',
    measurementId: 'G-BKV72E4YLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKxt9hKI60gjbZGHgU8bafN8iSHH3hqE',
    appId: '1:175735179668:android:a7a002d6b11b0a73a9e781',
    messagingSenderId: '175735179668',
    projectId: 'pawtrack-59d07',
    storageBucket: 'pawtrack-59d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1drq3DfZXc5c_lyC1XDDzkODPh0VXc0',
    appId: '1:175735179668:ios:cffa201b83b7abd8a9e781',
    messagingSenderId: '175735179668',
    projectId: 'pawtrack-59d07',
    storageBucket: 'pawtrack-59d07.firebasestorage.app',
    iosBundleId: 'com.example.dogWalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1drq3DfZXc5c_lyC1XDDzkODPh0VXc0',
    appId: '1:175735179668:ios:cffa201b83b7abd8a9e781',
    messagingSenderId: '175735179668',
    projectId: 'pawtrack-59d07',
    storageBucket: 'pawtrack-59d07.firebasestorage.app',
    iosBundleId: 'com.example.dogWalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBCuCUWenm0gZptXSbKZcHBycoxnyen0E',
    appId: '1:175735179668:web:395c90e10c3e39b9a9e781',
    messagingSenderId: '175735179668',
    projectId: 'pawtrack-59d07',
    authDomain: 'pawtrack-59d07.firebaseapp.com',
    storageBucket: 'pawtrack-59d07.firebasestorage.app',
    measurementId: 'G-W3LQ448FEM',
  );
}
